### ISSUE TITLE
NPE-crash: Thump/Warren appears to be case sensitive in channel names.

### ISSUE THREAD

**Issue by TomasKS** [WillowChat/Thump#37]
IRC messages with different (than Thump's own config...I guess) capitalization in the channel name makes Thump crash with an NPE-fault: 

[23:08:50] [Thread-1289/INFO] [Thump/]: Raw incoming line: :Ravenleft!Ravenleft@c-a78fe355.048-265-73746f34.cust.bredbandsbolaget.se PRIVMSG **#kin_guests** :Q, crash it again. Turned on raw IRC logging..maybe I can see what's going on
[23:08:50] [Thread-1289/INFO] [Thump/]: #kin_guests: <Ravenleft> Q, crash it again. Turned on raw IRC logging..maybe I can see what's going on
[23:09:07] [Thread-1289/INFO] [Thump/]: Raw incoming line: :Beer!Beer@c-a78fe355.048-265-73746f34.cust.bredbandsbolaget.se PRIVMSG **#Kin_Guests** :Tickle fight!
[23:09:07] [Thread-1289/INFO] [Thump/]: Uncaught exception from Warren thread - disconnecting: 
java.lang.NullPointerException
    at engineer.carrot.warren.thump.repack.warren.irc.handlers.core.PrivMsgHandler.handleMessage(PrivMsgHandler.java:45) ~[PrivMsgHandler.class:?]
    at engineer.carrot.warren.thump.repack.warren.irc.handlers.core.PrivMsgHandler.handleMessage(PrivMsgHandler.java:16) ~[PrivMsgHandler.class:?]
    at engineer.carrot.warren.thump.repack.warren.IncomingHandler.handleIRCMessage(IncomingHandler.java:181) ~[IncomingHandler.class:?]
    at engineer.carrot.warren.thump.repack.warren.IRCConnection.connect(IRCConnection.java:210) ~[IRCConnection.class:?]
    at engineer.carrot.warren.thump.connection.ConnectionWrapper.run(ConnectionWrapper.kt:151) ~[ConnectionWrapper.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[23:09:07] [Thread-1289/INFO] [Thump/]: Waiting for connection thread 'stratics' to finish...

This happens every time one specific user say something in the IRC-channel, he even tried different clients and devices (which made it look like it was something personal between him and Thump, lol) and we couldn't figure out what was going on as it works fine with everyone else. I was scratching my beard until I finally spotted the differences in the capitalization of the channel names, that has to be what's causing it.

I really like Thump so far so I hope you don't give up on it.

**Comment by skye-pp** [comment]
Thanks for reporting the error. I'm definitely not giving up on Thump - there's a huge amount of change coming soon (I wrote a better IRC framework from scratch in Kotlin).

I'll look at this issue tonight or tomorrow and fix it ASAP, and comment asking you to test it.

**Comment by skye-pp** [comment]
Could you also give me the details of the IRC network please? It helps for testing (bugs like these are usually from unexpected behaviour from IRC daemons).

**Comment by TomasKS** [comment]
I have a feature request, if you don't mind. Would it be possible to add some light bot functionality to Thump? Nothing complicated, just a command or two that prompts Thump to respond with information.

Something like: 
(IRC-user) /msg Thump !Help
(Thump) Minecraft server address is: this.server.here:25570
(Thump) Modpack: modpack.url
(Thump) Server map is at: map.server.location:1234

Where you configure the [optional] response(s) in thump.cfg or a separate response file. For simple security maybe a setting to require a password like /msg Thump !Help (password)

I find it curious that none of the IRC bridges I've used seem to have this, to me, obvious functionality. The server is in the IRC-channel anyway so it would be very convenient if it was able to tell users, on demand, how to connect to it.

Maybe this is a rare problem (or maybe this functionality exists and I just haven't found it) but for us it's always an issue, there's only 3-4 of us hanging out in the channel and we all have very different schedules and live in different time zones (from PST to CET) so relaying information mouth to mouth can be tedious at times plus we have a tendency to create new servers every now and then but often they end up just hanging out in the channel idling before anyone remembers to tell the others what it is and how to connect to it. 

Yeah, it would probably be better to set up a proper IRC-bot but for some reason that never gets done in our channel :)

The network is Stratics (irc.gamers-irc.org:6667/6668/7000) and it's running bahamut-1.4.34 as ircd

The server says this (and a lot of other things of course but this is the part that seem relevant) at logon:

[18:38] Welcome to the Stratics IRC Network Ravenleft!Ravenleft@c-dca872d5.048-265-73746f34.cust.bredbandsbolaget.se
[18:38] Your host is stratics.frws.com[@0.0.0.0], running version bahamut-1.4(34)

## [18:38] This server was created Thu May 3 2007 at 14:52:47 MDT

[18:38] stratics.frws.com bahamut-1.4(34) oiwscrknfydaAbghe biklLmMnoprRstvc

[18:38] NOQUIT WATCH=128 SAFELIST MAXCHANNELS=15 NICKLEN=30 TOPICLEN=307 NETWORK=Stratics SILENCE=10 CASEMAPPING=ascii are available on this server

Edit: Replaced < and > with ( and ) cause < and > makes the text inside invisible.

**Comment by lopcode** [comment]
I forgot to ask - what version of Thump and Minecraft are you using?

**Comment by lopcode** [comment]
I think I've fixed this issue for 1.8.9 and 1.9 versions. 1.7.10 is unsupported.

Could you try either of these?
- 1.8.9: https://hopper.bunnies.io/view/Warren/job/Thump/74/
- 1.9: https://hopper.bunnies.io/view/Warren/job/Thump-1.9/3/

**Comment by TomasKS** [comment]
Oh right, forgot versions as well. 
Minecraft 1.9 and Thump 2.2.2.2.

Just tried the Thump 2.2.2.3 and it didn't crash. I changed the capitalization of my own /join first to verify it really does crash 2.2.2.2 (it did) and then to verify it doesn't crash 2.2.2.3 (it didn't).

Thanks for the quick fix! An IRC-bridge becomes essential once you get used to it, playing without it feels like single player, heh.
